### ISSUE TITLE
RT0999: An item with the same key has already been added.

### ISSUE THREAD

**Issue by saraedum** [reinforced/Reinforced.Typings#99]
an invocation of `rtcli.exe` during msbuild fails with
```
Reinforced.Typings : Unexpected error RT0999: An item with the same key has already been added.
     at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
     at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
     at Reinforced.Typings.Cli.Bootstrapper.BuildReferencesCache()
     at Reinforced.Typings.Cli.Bootstrapper.GetAssembliesFromArgs()
     at Reinforced.Typings.Cli.Bootstrapper.InstantiateExportContext()
     at Reinforced.Typings.Cli.Bootstrapper.Main(String[] args)
```

~~The problem seems to be caused by an empty line at the end of the file that is passed to `rtcli.exe profile`.~~

The problem is caused by the following two lines in the profile that rtcli is reading:
```
D:\build\src\beta1194\packages\System.ValueTuple.4.5.0\lib\net47\System.ValueTuple.dll
C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.ValueTuple.dll
```

One of these is added explicitly by Npgsql.

Probably a duplicate of #28.

**Comment by pavel-b-novikov** [comment]
Well, I will try, but is your project okay with 2 different versions of ```System.ValueTuple```?

**Comment by pavel-b-novikov** [comment]
[`AssemblyManager` introduced in 1.5 must fix the issue](https://github.com/reinforced/Reinforced.Typings/blob/features-1.5/Reinforced.Typings.Cli/AssemblyManager.cs)

At least I have tried that with .NET Core 2.2 and Npgsql - it seems to be working
